// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DistributionChannel_DistribuiteSimpleTask_FullMethodName = "/distribution.DistributionChannel/DistribuiteSimpleTask"
	DistributionChannel_DistribuiteTask_FullMethodName       = "/distribution.DistributionChannel/DistribuiteTask"
)

// DistributionChannelClient is the client API for DistributionChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DistributionChannelClient interface {
	DistribuiteSimpleTask(ctx context.Context, in *SampleTaskMessage, opts ...grpc.CallOption) (*TaskStatus, error)
	DistribuiteTask(ctx context.Context, in *TaskMessage, opts ...grpc.CallOption) (*TaskStatus, error)
}

type distributionChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewDistributionChannelClient(cc grpc.ClientConnInterface) DistributionChannelClient {
	return &distributionChannelClient{cc}
}

func (c *distributionChannelClient) DistribuiteSimpleTask(ctx context.Context, in *SampleTaskMessage, opts ...grpc.CallOption) (*TaskStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStatus)
	err := c.cc.Invoke(ctx, DistributionChannel_DistribuiteSimpleTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributionChannelClient) DistribuiteTask(ctx context.Context, in *TaskMessage, opts ...grpc.CallOption) (*TaskStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStatus)
	err := c.cc.Invoke(ctx, DistributionChannel_DistribuiteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistributionChannelServer is the server API for DistributionChannel service.
// All implementations must embed UnimplementedDistributionChannelServer
// for forward compatibility.
type DistributionChannelServer interface {
	DistribuiteSimpleTask(context.Context, *SampleTaskMessage) (*TaskStatus, error)
	DistribuiteTask(context.Context, *TaskMessage) (*TaskStatus, error)
	mustEmbedUnimplementedDistributionChannelServer()
}

// UnimplementedDistributionChannelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDistributionChannelServer struct{}

func (UnimplementedDistributionChannelServer) DistribuiteSimpleTask(context.Context, *SampleTaskMessage) (*TaskStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistribuiteSimpleTask not implemented")
}
func (UnimplementedDistributionChannelServer) DistribuiteTask(context.Context, *TaskMessage) (*TaskStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistribuiteTask not implemented")
}
func (UnimplementedDistributionChannelServer) mustEmbedUnimplementedDistributionChannelServer() {}
func (UnimplementedDistributionChannelServer) testEmbeddedByValue()                             {}

// UnsafeDistributionChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistributionChannelServer will
// result in compilation errors.
type UnsafeDistributionChannelServer interface {
	mustEmbedUnimplementedDistributionChannelServer()
}

func RegisterDistributionChannelServer(s grpc.ServiceRegistrar, srv DistributionChannelServer) {
	// If the following call pancis, it indicates UnimplementedDistributionChannelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DistributionChannel_ServiceDesc, srv)
}

func _DistributionChannel_DistribuiteSimpleTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleTaskMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributionChannelServer).DistribuiteSimpleTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributionChannel_DistribuiteSimpleTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributionChannelServer).DistribuiteSimpleTask(ctx, req.(*SampleTaskMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributionChannel_DistribuiteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributionChannelServer).DistribuiteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributionChannel_DistribuiteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributionChannelServer).DistribuiteTask(ctx, req.(*TaskMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// DistributionChannel_ServiceDesc is the grpc.ServiceDesc for DistributionChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DistributionChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distribution.DistributionChannel",
	HandlerType: (*DistributionChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DistribuiteSimpleTask",
			Handler:    _DistributionChannel_DistribuiteSimpleTask_Handler,
		},
		{
			MethodName: "DistribuiteTask",
			Handler:    _DistributionChannel_DistribuiteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
